### ISSUE TITLE
Notion Page Not Found

### ISSUE THREAD

**Issue by Mvbbb** [transitive-bullshit/nextjs-notion-starter-kit#53] opened 2021-02-16 03:28 UTC
# Notion Page Not Found

I can't open a page in my site which address is https://www.yzh.im/java-webserver, and the root document address is https://www.notion.so/Java-WebServer-6ea6cff13423406dbf6e3e54f2ea9fc4. 

![image](https://user-images.githubusercontent.com/56795364/108014671-5c655380-7049-11eb-86df-332be43cd0de.png)

I don't know why this happened and I did not modify any source code related to this phenomenon.

my site source code address is https://github.com/Mvbbb/nextjs-notion-blog

**Comment by Mvbbb** [comment] 2021-02-16 03:50
Error loading page problem seems be disappeared，I can open this page on my phone, really waired. but the content still did not update .

**Comment by transitive-bullshit** [comment] 2021-02-16 04:36
Hmmm, https://www.yzh.im/6ea6cff13423406dbf6e3e54f2ea9fc4 seems to work, so it's just the short URLs that aren't working for you.

Your site automatically generates a [sitemap](https://www.yzh.im/api/sitemap.xml) which tells you everything you need to know about which URLs are available at build time, so something's going wrong with your canonical short URLs.

First suggestion: make sure your fork is on the latest version of the code, because this repo has been making a lot of progress over the last week or so.

**Comment by Mvbbb** [comment] 2021-02-16 06:12
> Hmmm, [yzh.im/6ea6cff13423406dbf6e3e54f2ea9fc4](https://www.yzh.im/6ea6cff13423406dbf6e3e54f2ea9fc4) seems to work, so it's just the short URLs that aren't working for you.
> 
> Your site automatically generates a [sitemap](https://www.yzh.im/api/sitemap.xml) which tells you everything you need to know about which URLs are available at build time, so something's going wrong with your canonical short URLs.
> 
> First suggestion: make sure your fork is on the latest version of the code, because this repo has been making a lot of progress over the last week or so.

Thanks，i'll try.

**Comment by Mvbbb** [comment] 2021-02-16 07:59
I'm using the latest version of code, but here comes another problem. When I run dev locally on my computer, I was try to open a page, an error happened.

```
event - build page: /_error
wait  - compiling...
event - compiled successfully
TypeError: Cannot read property 'find' of undefined
    at E:\Desktop\nextjs-notion-starter-kit\node_modules\react-notion-x\build\cjs\components\property.js:77:53
    at Array.map (<anonymous>)
    at Property (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-notion-x\build\cjs\components\property.js:76:38)
    at processChild (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
    at resolve (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at renderToString (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at Object.renderPage (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\render.js:54:851)
    at Function.getInitialProps (E:\Desktop\nextjs-notion-starter-kit\.next\server\pages\_document.js:293:19)
    at loadGetInitialProps (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\lib\utils.js:5:101)
    at renderToHTML (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\render.js:54:1142)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\next-server.js:107:97
    at async __wrapper (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\next-server.js:132:387)
NotionAPI collectionQuery error Client network socket disconnected before secure TLS connection was established
```
Although this page was successfully loaded, but part of content disappeared. And this page's address in notion is https://www.notion.so/de4173f92b6b421a85d15e1fba9da96a.
![image](https://user-images.githubusercontent.com/56795364/108031611-208fb580-706c-11eb-8b6f-49cc4ffaf22c.png)
Then I was try to push to vercel but builded failed. Then I removed this post from notion page, build success. I guess it is this post caused the build failed, but why?

You can see the page that caused the build failed through https://www.notion.so/de4173f92b6b421a85d15e1fba9da96a.  
Build failure logs:  https://gitee.com/mvbbb/pichost/raw/master/20210216155713.txt
And my notion page address is https://www.notion.so/Mvbbb-s-Notes-bbfb38bf9a0348f89bb4078b0f7d7cca.  
Source code address: https://github.com/Mvbbb/nextjs-notion-blog

**Comment by Mvbbb** [comment] 2021-02-16 08:19
> > Hmmm, [yzh.im/6ea6cff13423406dbf6e3e54f2ea9fc4](https://www.yzh.im/6ea6cff13423406dbf6e3e54f2ea9fc4) seems to work, so it's just the short URLs that aren't working for you.
> > Your site automatically generates a [sitemap](https://www.yzh.im/api/sitemap.xml) which tells you everything you need to know about which URLs are available at build time, so something's going wrong with your canonical short URLs.
> > First suggestion: make sure your fork is on the latest version of the code, because this repo has been making a lot of progress over the last week or so.
> 
> Thanks，i'll try.

I udpated to the latest version. But It seemed that this problem still exists, in sitemap do not have this url :https://www.yzh.im/java-webserver. Then I changed the title from "使用 Java 实现简单的 Webserver" into "java-webserver", I can visit this page successfully. If there has a bug when generating the canonical short URLs?

**Comment by transitive-bullshit** [comment] 2021-02-16 16:10
This may be a problem with chinese character support; i'm not sure but will look into it later today.

**Comment by Mvbbb** [comment] 2021-02-18 01:26
> I'm using the latest version of code, but here comes another problem. When I run dev locally on my computer, I was try to open a page, an error happened.
> 
> ```
> event - build page: /_error
> wait  - compiling...
> event - compiled successfully
> TypeError: Cannot read property 'find' of undefined
>     at E:\Desktop\nextjs-notion-starter-kit\node_modules\react-notion-x\build\cjs\components\property.js:77:53
>     at Array.map (<anonymous>)
>     at Property (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-notion-x\build\cjs\components\property.js:76:38)
>     at processChild (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3353:14)
>     at resolve (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3270:5)
>     at ReactDOMServerRenderer.render (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3753:22)
>     at ReactDOMServerRenderer.read (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
>     at renderToString (E:\Desktop\nextjs-notion-starter-kit\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
>     at Object.renderPage (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\render.js:54:851)
>     at Function.getInitialProps (E:\Desktop\nextjs-notion-starter-kit\.next\server\pages\_document.js:293:19)
>     at loadGetInitialProps (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\lib\utils.js:5:101)
>     at renderToHTML (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\render.js:54:1142)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at async E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\next-server.js:107:97
>     at async __wrapper (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\lib\coalesced-function.js:1:330)
>     at async DevServer.renderToHTMLWithComponents (E:\Desktop\nextjs-notion-starter-kit\node_modules\next\dist\next-server\server\next-server.js:132:387)
> NotionAPI collectionQuery error Client network socket disconnected before secure TLS connection was established
> ```
> 
> Although this page was successfully loaded, but part of content disappeared.
> ![image](https://user-images.githubusercontent.com/56795364/108031611-208fb580-706c-11eb-8b6f-49cc4ffaf22c.png)
> Then I was try to push to vercel but builded failed. Then I removed this post from notion page, build success. **I guess it is this post that caused the build failure**, but why?
> 
> You can see the page that caused the build failed through [notion.so/de4173f92b6b421a85d15e1fba9da96a](https://www.notion.so/de4173f92b6b421a85d15e1fba9da96a).
> Build failure logs: [gitee.com/mvbbb/pichost/raw/master/20210216155713.txt](https://gitee.com/mvbbb/pichost/raw/master/20210216155713.txt)
> And my notion page address is [notion.so/Mvbbb-s-Notes-bbfb38bf9a0348f89bb4078b0f7d7cca](https://www.notion.so/Mvbbb-s-Notes-bbfb38bf9a0348f89bb4078b0f7d7cca)
> Source code address: [Mvbbb/nextjs-notion-blog](https://github.com/Mvbbb/nextjs-notion-blog)

I knew the reason for the failure of the build. I opened the tags property for list view, but I did not add any tag for those article. So just make sure you tags property for list view is closed if you don't add tags to you article. 
![image](https://user-images.githubusercontent.com/56795364/108290292-09b3a500-71cb-11eb-99bf-7b437554c535.png)

**Comment by jorgeruvalcaba** [comment] 2021-03-08 15:50
I had the same issue and I could solve it by enabling the tags option as well.

**Comment by transitive-bullshit** [comment] 2021-03-08 16:25
@Mvbbb @jorgeruvalcaba `TypeError: Cannot read property 'find' of undefined for property.js` was definitely a bug in `react-notion-x`.

Thanks for bringing it to my attention; just fixed in `v4.3.3`.

I think the "notion page not found" error is a separate issue likely dealing with the canonical short URLs. I'll try looking into it when I find some time.

In the meantime, any additional context that you can provide that'll make it easier to reproduce the issue would be really helpful.

Thanks!

**Comment by jorgeruvalcaba** [comment] 2021-03-08 23:28
This issue is only happening to me just on the production site: https://jorgeruvalcaba.dev/add-tab-to-search-in-your-gatsby-blog. Local env works fine ✅ .

**Comment by CryogenicPlanet** [comment] 2021-03-11 03:35
Have the same issue here https://docs.modfy.video/compress

But this link https://docs.modfy.video/compress-3c3215882a4747ca8b2e2fd4a602cb9a works fine

Original notion https://www.notion.so/modfy/Compress-3c3215882a4747ca8b2e2fd4a602cb9a

@transitive-bullshit As a quick fix is there a way to disable the short URL for production?

**Comment by jorgeruvalcaba** [comment] 2021-03-11 17:03
@CryogenicPlanet as a workaround you can update the `pageUrlOverrides` option in your `site.config.js` file. It would be something like:

```
pageUrlOverrides: {
  '/compress': '3c3215882a4747ca8b2e2fd4a602cb9a',
}
```

Hope that this helps!

**Comment by jorgeruvalcaba** [comment] 2021-03-11 20:59
@transitive-bullshit after doing a little research this is what I found:

After clicking on any page in prod, the page asks for the page props to `resolveNotionPage`. There, the `pageId` is never defined because the `siteMap` generated doesn't contain the data for the `rawPageId` which always returns a `siteMap` for the root page. In my case, I'm not providing any `rootNotionSpaceId` so the `rootNotionPageId` is being used as the spaceId. `getSiteMaps` calls `getAllPages` which uses `getAllPagesInSpace`which always returns a `pageMap` for the `rootNotionPageId`. I've also tried using `roontNotionSpaceId` and it returns nothing in this case. So I think the issue is this `getAllPagesInSpace` function from `react-notion-x/notion-utils`.

Let me know if this makes sense so I can create another issue in the `react-notion-x` repo.

**Comment by CryogenicPlanet** [comment] 2021-03-12 13:18
> @CryogenicPlanet as a workaround you can update the `pageUrlOverrides` option in your `site.config.js` file. It would be something like:
> 
> ```
> pageUrlOverrides: {
>   '/compress': '3c3215882a4747ca8b2e2fd4a602cb9a',
> }
> ```
> 
> Hope that this helps!

@jorgeruvalcaba Actually there are a few pages like this, found 4-5 like this and as we keep adding pages worried that more might break, so it would be great if there was a universal toggle.

**Comment by Ashinch** [comment] 2021-04-15 07:27
Non-English characters are ignored in URLs. If you can convert the URL characters to Unicode, this will solve the problem

**Comment by miaogaolin** [comment] 2022-03-01 04:00
The solution is here：https://github.com/miaogaolin/notion-blog/pull/3
Reason：https://github.com/NotionX/react-notion-x/issues/176

**Comment by transitive-bullshit** [comment] 2022-03-26 08:17
@CryogenicPlanet set `includeNotionIdInUrls` to `true` in your site config.

I think there are multiple, separate issues people are commenting on in this thread. I've fixed `getPageProperty` in the latest update to never throw, so that should fix a lot of these issues.

If you're having a similar problem, please open a new issue, include your notion page ID, and I'll try to reproduce the issue.

Thanks!

**Closed by transitive-bullshit** 2022-03-26 08:17 UTC
