### ISSUE TITLE
HTTPError: Response code 418 (I'm a Teapot)

### ISSUE THREAD

**Issue by yanyanlongxia** [transitive-bullshit/nextjs-notion-starter-kit#42] opened 2021-02-04 03:39 UTC
I want to enable preview image support, so I set up my firebase.
But when I was deploying, Vercel told me
```

page load error {
--
11:18:07.713 | pageId: '123b34e0-320e-42a8-b02e-3af7553a2bbc',
11:18:07.713 | spaceId: 'f225ce83-48e1-4217-8126-c47ff80789dc'
11:18:07.713 | } HTTPError: Response code 418 (I'm a Teapot)
11:18:07.713 | at Request.<anonymous> (/vercel/workpath3/node_modules/got/dist/source/as-promise/index.js:117:42)
11:18:07.713 | at processTicksAndRejections (internal/process/task_queues.js:97:5) {
11:18:07.713 | code: undefined,
11:18:07.713 | timings: {
11:18:07.713 | start: 1612408687533,
11:18:07.713 | socket: 1612408687534,
11:18:07.713 | lookup: 1612408687558,
11:18:07.713 | connect: 1612408687569,
11:18:07.713 | secureConnect: 1612408687595,
11:18:07.713 | upload: 1612408687595,
11:18:07.713 | response: 1612408687710,
11:18:07.713 | end: 1612408687710,
11:18:07.713 | error: undefined,
11:18:07.713 | abort: undefined,
11:18:07.713 | phases: {
11:18:07.713 | wait: 1,
11:18:07.713 | dns: 24,
11:18:07.713 | tcp: 11,
11:18:07.713 | tls: 26,
11:18:07.713 | request: 0,
11:18:07.713 | firstByte: 115,
11:18:07.713 | download: 0,
11:18:07.714 | total: 177
11:18:07.714 | }
11:18:07.714 | }
11:18:07.714 | }

```
When I disabled the preview image support, it went back to normal.

This is the content in vercel.json
![imag1.png](https://i.ibb.co/HKJdd13/Snipaste-2021-02-04-11-31-12.png)

Here is the information from firestore
![imag2.png](https://i.ibb.co/s1G3fZn/Snipaste-2021-02-04-11-35-01.png)

This is the firestore rule:
![imag3.png](https://i.ibb.co/CVccJw7/Snipaste-2021-02-04-11-37-14.png)

[The full Vercel output](https://pastebin.ubuntu.com/p/f3nQ4sF2jB/)

Do you know what is wrong?

**Comment by transitive-bullshit** [comment] 2021-02-04 04:04
I think this error is coming from here: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/api/create-preview-image.ts#L19

If you add your env variables into a local `.env.build` file (maybe also a `.env` file which is what I do), and then run `vercel dev`, does it work for you locally?

My advice is to try getting the preview images working locally before deploying to vercel.

**Comment by yanyanlongxia** [comment] 2021-02-04 07:14
I ran it locally by ``vercel dev`` and it turned it a ``404 Error``?  Do you know what's wrong?

I've turned the domain into ``localhost``

![imag1.png](https://i.ibb.co/ss4gQ3H/Snipaste-2021-02-04-15-11-44.png)

![imag2.png](https://i.ibb.co/kB7XbNC/Snipaste-2021-02-04-15-13-52.png)

**Comment by yanyanlongxia** [comment] 2021-02-04 07:27
Also, after I disabled preview image support, it went back to normal.

There is also an error message ``Error! Failed to complete request to /_next/webpack-hmr?page=%2F: Error: socket hang up``

**Comment by wujunchuan** [comment] 2021-02-09 18:18
I post request manually, the response is success.

![image](https://user-images.githubusercontent.com/7511631/107408599-248c7680-6b46-11eb-8d4a-0a9a0a6384c9.png)

ps: But `vercel dev` mode, it doesn't work.

> I ran it locally by `vercel dev` and it turned it a `404 Error`? Do you know what's wrong?
> 
> I've turned the domain into `localhost`
> 
> ![imag1.png](https://camo.githubusercontent.com/695f8f9df45c88d871d5541e29d90237ac4f445bbf3e5e51bc9d542cf747159e/68747470733a2f2f692e6962622e636f2f737334675133482f536e6970617374652d323032312d30322d30342d31352d31312d34342e706e67)
> 
> ![imag2.png](https://camo.githubusercontent.com/51a5f9fa65a9dc658557cff8b656024ffdb1e0965c92e9638bf7c0b0f41d55a2/68747470733a2f2f692e6962622e636f2f6b423758624e432f536e6970617374652d323032312d30322d30342d31352d31332d35322e706e67)

**Comment by Tirth27** [comment] 2021-02-21 07:30
Hello @transitive-bullshit I am getting `Firebase config error: invalid "GOOGLE_APPLICATION_CREDENTIALS" should be base64-encoded JSON`

Did you have any guide to how to configure one. 

Thank you in Advance.

**Comment by transitive-bullshit** [comment] 2021-02-21 20:44
If you're on macOS, you can run:

```bash
cat my-google-application-credentials-file.json | base64 | pbcopy
```

And the result will be in your clipboard.

**Comment by bcanata** [comment] 2021-02-21 21:07
I'm also getting:

```
00:02:24.382 | page error notlar.im notlarim HTTPError: Response code 418 (I'm a Teapot)
-- | --
00:02:24.382 | at Request.<anonymous> (/vercel/workpath2/node_modules/got/dist/source/as-promise/index.js:117:42)
00:02:24.383 | at processTicksAndRejections (internal/process/task_queues.js:93:5) {
```

My token json file is base64 encoded and correct. If I mistype it, I receive:

`Firebase config error: invalid "GOOGLE_APPLICATION_CREDENTIALS" should be base64-encoded JSON`

So the 418 error is caused by another problem, I guess.

**Comment by dbredvick** [comment] 2021-03-26 22:29
Okay, a few common causes of this:

1. Your URL is set to the wrong address in `site.config.js`
2. Your deployed API function is set to `isPreviewImageSupportEnabled: false`
3. ?? not sure if in build the localhost:3000/api/generate works??

A few quick fixes:
1. set `isPreviewImageSupportEnabled: true` 
2. comment out lines 48-50 of `notion.ts` (the image stuff)
3. deploy it

Then after that deployment finishes,
1. uncomment out lines 48-50
2. set the site domain in `site.config.js` to the output of your Vercel build (e.g. blog-drab-alpha.vercel.app)
3. deploy again

That path fixed everything for me. Am going to look further into the root cause later.

**Comment by Tirth27** [comment] 2021-03-27 05:48
Hi @dbredvick, Thank you for your response. 

I have tried to follow your steps but it is still not working for me. I have provided the vercel for debugging. 
[vercel_deploy_logs.txt](https://github.com/transitive-bullshit/nextjs-notion-starter-kit/files/6215178/vercel_deploy_logs.txt)

Hope it helps.

**Comment by minhthongdoan** [comment] 2021-06-28 05:17
Hello @yanyanlongxia @Tirth27. In my case, it's returning 418 error because the Node.js version in Vercel is 14.x. After going to the Vercel's project setting, change Node.js version to 12.x, the error disappears and preview image support works flawlessly.

**Comment by dalaomai** [comment] 2021-07-15 14:47
it look like about custom domain.when i remove my domain in Vercel, everything ok !!

**Comment by YamenSharaf** [comment] 2022-01-08 20:15
Did anyone figure out a way around this? I'm also using a custom domain and when I run locally I'm getting the same 404 error and when deploying getting the teapot error

**Comment by m0rtyn** [comment] 2022-02-06 14:16
@Tirth27 
Hi, it was helpful for me to find this instruction for getting Gcloud service credentials, not Firebase config object ⇾ https://cloud.google.com/docs/authentication/getting-started#creating_a_service_account

@transitive-bullshit
I can add this instruction to README file

But when I solved the first problem, I faced with "status 418" error, and when I downgraded to node 12 then I get "Error occurred prerendering page" with custom page URLs from site.config. So I don't know what to do to fix image previews 🤷‍♂️

**Comment by Dmitry-zh** [comment] 2022-03-18 20:11
This message was prepared with the help of a translator, so I apologize in advance.

Firstly, I considered it right to wrap firebase API calls in a try catch construct (ib/get-preview-images.ts 21-24, 30)
Then the api/create-preview-image call was also wrapped in a try catch to get results and filter out nullable
This already solves the build problem if some image didn't load in firebase.

In the future, I plan to stop calling /api/create-preview-image. Since it requires an upstream server, it causes errors if the build runs on the same port.
Instead, 'create-preview-image' should be moved to lib and call the firebase API from there to load the image

**Comment by transitive-bullshit** [comment] 2022-03-26 08:07
The latest version has switched to using a much simpler approach for image caching, and this API route no longer exists.

Please upgrade to the latest to fix this issue.

**Closed by transitive-bullshit** 2022-03-26 08:07 UTC
