### ISSUE TITLE
how do i export static site to deploy myself host ？

### ISSUE THREAD

**Issue by Anthony-Duan** [transitive-bullshit/nextjs-notion-starter-kit#36] opened 2021-01-31 14:30 UTC
I have a host,and i want use this kit export static file and then deploy use Nginx .
I adjust  one place in package.json. but I have a trouble ,
![image](https://user-images.githubusercontent.com/31313340/106387215-b5ab7100-6413-11eb-8fa5-6dce574288d3.png)
![image](https://user-images.githubusercontent.com/31313340/106387236-c825aa80-6413-11eb-9dac-3047703b5d77.png)

**Comment by transitive-bullshit** [comment] 2021-01-31 18:31
Hey Anthony 👋 

This is really more of a question for [Next.js discussions](https://github.com/vercel/next.js/discussions), but I'll try to answer here.

You can remove this line to solve your issue: https://github.com/transitive-bullshit/nextjs-notion-starter-kit/blob/main/pages/%5BpageId%5D.tsx#L47

What this is doing is telling Next.js to allow for any unknown Notion pages to be resolved in addition to the pages that are known when initially deploying your site. But this is really optional. It just means that if you add new pages in Notion, they won't resolve on your site until you redeploy, which is what's necessary if you're using `next export`.

**Closed** 2021-02-04 02:32 UTC

**Comment by SantoshSrinivas79** [comment] 2021-09-28 08:40
Hi @zhijian-pro 

I am getting the below error for export. Any suggestion if you have been able to get the export to work?

<img width="857" alt="Screenshot 2021-09-28 at 2 09 21 PM" src="https://user-images.githubusercontent.com/1036163/135053685-1465eeb3-cac1-47b5-ad75-f6c96946cdce.png">

Thank you!

**Comment by andresjz** [comment] 2022-01-30 03:12
Just to help someone else in the future: 
The support that `next.js` + `vercel` provide it's wider than if you plan to hosting your site outside check details: https://nextjs.org/docs/deployment

Now the issues:

1. `next/image` : dependency is used by "react-static-tweets": "^0.5.3", and "static-tweets": "^0.5.3", at this point I just removed them, in order to avoid that issue, however I would like to take a look of this and if that is allowed I can file a PR.
Reference: https://nextjs.org/docs/messages/export-image-api


2. `fallback` enabled in `getStaticPaths`: the problem is that once you build the static side, you cannot take advantage of next.js capabilites,  check this link: https://nextjs.org/docs/messages/ssg-fallback-true-export

Then you need to disable fallback
 
```
fallback: false 
```
