### ISSUE TITLE
Social Image API fails for some pages

### ISSUE THREAD

**Issue by soumendrak** [transitive-bullshit/nextjs-notion-starter-kit#385] opened 2022-10-15 02:23 UTC
#### Description

Even after the implementation of #383 social images are not coming as expected. Only a blank white background webpage is coming if you click on the below-mentioned social-image URL.

#### Notion Test Page ID

Notion site: https://soumendrak.notion.site/Sam-Manekshaw-b0a982ee52304e9397f09c25c06b4c4f
Page ID: b0a982ee52304e9397f09c25c06b4c4f

#### Social Image URL
https://www.soumendrak.com/api/social-image?id=b0a982ee-5230-4e93-97f0-9c25c06b4c4f

#### Vercel Function logs

```
[GET] /api/social-image?id=b0a982ee-5230-4e93-97f0-9c25c06b4c4f
07:48:01:99
Function Status: 200
Edge Status: 200
Duration: N/A
Init Duration: N/A
Memory Used: N/A
ID: bom1::8mtkt-1665800281509-5afceb24b71f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42

[GET] /api/social-image?id=b0a982ee-5230-4e93-97f0-9c25c06b4c4f status=200
```
![image](https://user-images.githubusercontent.com/10120538/195964590-c9c8829a-1f21-4df2-908a-e72c8d5652cb.png)

#### Forked GitHub
https://github.com/soumendrak/soumendrak.com

@transitive-bullshit please check 🙏🏼

**Comment by transitive-bullshit** [comment] 2022-10-15 03:48
Thanks for the report @soumendrak. Definitely looks like a bug; I'll investigate this tomorrow.

**Comment by transitive-bullshit** [comment] 2022-10-15 04:26
I've committed a workaround to `main`. Here's a live example working with your page: https://nextjs-notion-starter-kit.transitivebullsh.it/api/social-image?id=b0a982ee-5230-4e93-97f0-9c25c06b4c4f

The issue is that this page uses a really large external unsplash image (2.8MB): https://images.unsplash.com/photo-1610816168075-f19d937635f5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb

The workaround is to make sure that unsplash images have a bounded width: https://images.unsplash.com/photo-1610816168075-f19d937635f5?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=2000&fit=max

This isn't a guaranteed fix for all use cases, since notion pages can have arbitrarily large cover images, but due to the strict [limitations](https://vercel.com/docs/concepts/functions/edge-functions/limitations) of Vercel edge functions, my advice for these cases will be to run any excessively large background images through an image optimizer.

We'll need to figure out how common this edge case is and decide how best to proceed. At the very least, the OG image shouldn't be returning `200` in these cases, and it's unclear why this is happening (my hunch is that it's somewhere in Satori).

**Comment by soumendrak** [comment] 2022-10-15 05:28
Thank you @transitive-bullshit for the _surprise_ quick fix 🥇 
It's working now 💯 
> my advice for these cases will be to run any excessively large background images through an image optimizer.

Do you recommend any specific tool for image optimization?

**Comment by transitive-bullshit** [comment] 2022-10-15 13:14
> Do you recommend any specific tool for image optimization?

https://optimage.app is my favorite (if you have a mac).

**Comment by nooobcoder** [comment] 2022-10-17 05:00
@soumendrak use this tool if you're are on windows
https://bluefive.pairsite.com/pixresizer.htm

**Comment by soumendrak** [comment] 2022-10-17 08:29
Thanks @transitive-bullshit and @nooobcoder for the suggestions.

**Comment by transitive-bullshit** [comment] 2022-11-04 18:22
Going to close this for now as an upstream issue.

**Closed by transitive-bullshit** 2022-11-04 18:22 UTC
