### ISSUE TITLE
safari bug grid

### ISSUE THREAD

**Issue by ToledoNicola** [transitive-bullshit/nextjs-notion-starter-kit#60] opened 2021-02-23 09:48 UTC
on safari
<img width="1216" alt="Schermata 2021-02-23 alle 10 46 58" src="https://user-images.githubusercontent.com/32549447/108826444-92b04f00-75c4-11eb-8aaa-dc1a0b9d818e.png">

on chrome
<img width="1552" alt="Schermata 2021-02-23 alle 10 45 59" src="https://user-images.githubusercontent.com/32549447/108826468-9a6ff380-75c4-11eb-8134-029719deee1d.png">

**Comment by transitive-bullshit** [comment] 2021-03-01 19:59
Thanks @ToledoNicola; this is a duplicate of https://github.com/NotionX/react-notion-x/issues/30, so I'm going to close it for now.

Will hopefully have a fix in `react-notion-x` soon.

**Closed by transitive-bullshit** 2021-03-01 19:59 UTC

**Comment by normdoow** [comment] 2021-03-01 23:46
Just making a fix for this now.
